---
after_script:
- ruby -Ilib bin/rake travis:after -t
before_script:
- gem install hoe-travis --no-document
- gem install minitest -v '~> 5.0' --no-document
- ruby -Ilib bin/rake travis:before -t
language: ruby
sudo: false
notifications:
  email:
  - drbrain@segment7.net
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-1.7.20
  - jruby-9.0.4.0
  - jruby-head
  - rbx-2
script: ruby -Ilib bin/rake
matrix:
  allow_failures:
    - rvm: jruby-1.7.20
    - rvm: jruby-9.0.4.0
    - rvm: jruby-head
