language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby-1.7.26
  - jruby-9.1.6.0
  - jruby-head
before_install:
  - gem install bundler --no-document -v '~> 1.13.3'
before_script:
  - unset JRUBY_OPTS
script: ruby -Ilib exe/rake
notifications:
  email:
  - hsbt@ruby-lang.org
  - drbrain@segment7.net
