---
after_script:
- ruby -Ilib bin/rake travis:after -t
before_script:
- gem install hoe-travis --no-rdoc --no-ri
- ruby -Ilib bin/rake travis:before -t
language: ruby
notifications:
  email:
  - drbrain@segment7.net
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
script: ruby -Ilib bin/rake
