name: win32

on: [push, pull_request]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      min_version: 2.3
      engine: cruby-jruby
      versions: '["truffleruby"]'

  win32-system-dir:
    needs: ruby-versions
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        exclude:
          - ruby: truffleruby
          - ruby: jruby-head
          - ruby: jruby
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: ruby/setup-ruby@d5126b9b3579e429dd52e51e68624dda2e05be25 # v1.267.0
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Run "win32_system_dir" comparison
      run: .\win32_system_dir.bat
      shell: cmd
